---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: terraform-plan
  namespace: terraform
spec:
  inputs:
    resources:
      - name: src
        type: git
  steps:
    - name: terraform-plan
      image: hashicorp/terraform:latest
      workingDir: /workspace/src/terraform
      script: |
          #! /bin/sh
          terraform init
          terraform plan

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: terraform-apply
  namespace: terraform
spec:
  inputs:
    resources:
      - name: src
        type: git
  steps:
    - name: terraform-apply
      image: hashicorp/terraform:latest
      workingDir: /workspace/src/terraform
      script: |
          #! /bin/sh
          terraform init
          terraform apply --auto-approve
